### ISSUE TITLE
Multiple problems with the template

### ISSUE THREAD

**Issue by ytcalifax** [jekyllt/jasper2#103]
**Describe the bug**
The template design gets broken when opening some of the pages. Moreover, the author's list is broken and leads to a 404 page.

**To Reproduce**

* Broken page design
1. Open the one of the tags pages
2. Look at the page

* 404 Page
1. Make a post
2. Click on the author's name
3. Look at the page

**Expected behavior**
The pages should be rendered properly. No 404 should occur when browsing to the author info page.

**Environment:**
 - OS: Windows 10 (1903)
 - Ruby: Ruby+Devkit 2.6.5-1 (x64)
 - Browser: Brave Browser 80.0.3987.132 (x64)

**Comment by mrsequeira** [comment]
I'm having the same issue ☝️ 
The additional information from the above reported:

- Forked the repository from the last commit https://github.com/jekyller/jasper2/commit/af70413924c300549107b13c750cf1c87ef78c53 without any additional commit but still have the same issues

**Comment by biomadeira** [comment]
@ytcalifax As others have commented on other issues, you need to play with the [baseurl](https://github.com/jekyller/jasper2/blob/80360013a1f166c11bc0fb0aba3f64e1966bb0a5/_config.yml#L9). There is a difference when running a project-based site (e.g. jekyller.github.io/jasper2/) and a personal site (e.g. username.github.io/). Could you try that?
